### ISSUE TITLE
Set flake8 configuration in setup.cfg

### ISSUE THREAD

**Issue by stephankramer** [pyroteus/animate#65]
Adding this in setup.cfg, instead of through command-line options in the Makefile, means flake8 checks do the right thing in IDEs (and in my own vim short-cuts)

**Comment by stephankramer** [comment]
Oh I see you're using .flake8 in goalie. Maybe I should just copy that instead?

**Comment by jwallwork23** [comment]
> Oh I see you're using .flake8 in goalie. Maybe I should just copy that instead?

That'd be great if you wouldn't mind, thanks.
